# Site settings
title: Billy Purvis | Front-End Developer In London
email: purvisbilly@outlook.com
description: "Front-End Developer based in London, England. I work with jekyll, gulp, sass, javascript, jQuery and more"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://billypurvis.github.io" # the base hostname & protocol for your site
root: "../"
twitter_username: mrmonkeytech
github_username:  BillyPuris

# Blog Settings
permalink: /blog/:title/
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# excludes
exclude: [node_modules]
